#!/bin/bash

if [ -f tobii/sdk/include/tobiigaze.h ]; then
    cd tobii
    qmake eyetracker-tobii.pro
    make -j4
    cd ..
else
    echo No Tobii Gaze SDK detected.
fi

mkdir -p bin

if [ -f tobii/eyetracker-tobii-preview ]; then
    cp tobii/eyetracker-tobii-preview bin/eyetracker-tobii-preview
fi

